# Generated by Django 3.2.16 on 2023-01-12 23:46

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testnet_name', models.CharField(max_length=60, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='testnet_name', unique=True)),
                ('network_name', models.CharField(max_length=25)),
                ('network_status', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=25)),
                ('twitter', models.CharField(max_length=25)),
                ('facebook', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=25)),
                ('discord', models.CharField(max_length=25)),
                ('telegram', models.CharField(max_length=25)),
                ('instagram', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=120)),
                ('whitepaper', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=25)),
                ('tasks_description', models.TextField()),
                ('wallet1_name', models.CharField(max_length=25)),
                ('wallet1_type', models.CharField(max_length=25)),
                ('wallet1_link', models.CharField(max_length=255)),
                ('wallet2_name', models.CharField(max_length=25)),
                ('wallet2_type', models.CharField(max_length=25)),
                ('wallet2_link', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('copied_nb', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testnets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('exp', models.IntegerField(default=100)),
                ('status', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0)),
                ('debank', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('avatar', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TestnetUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet1_adress', models.CharField(max_length=255)),
                ('wallet1_seed', models.CharField(default='none', max_length=255)),
                ('wallet1_priv_key', models.CharField(default='none', max_length=255)),
                ('wallet1_password', models.CharField(default='none', max_length=30)),
                ('wallet1_session', models.CharField(default='none', max_length=30)),
                ('wallet1_clue', models.TextField(blank=True)),
                ('wallet2_adress', models.CharField(default='none', max_length=255)),
                ('wallet2_seed', models.CharField(default='none', max_length=255)),
                ('wallet2_priv_key', models.CharField(default='none', max_length=255)),
                ('wallet2_password', models.CharField(default='none', max_length=30)),
                ('wallet2_session', models.CharField(default='none', max_length=30)),
                ('wallet2_clue', models.TextField(blank=True)),
                ('twitter', models.CharField(max_length=21)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=25)),
                ('discord', models.CharField(max_length=25)),
                ('telegram', models.CharField(max_length=25)),
                ('browser', models.CharField(max_length=25)),
                ('tasks_results', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('testnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testnet_user_info', to='app.testnet')),
                ('testnet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testnet_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('read', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0)),
                ('notification_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('checklist_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
