# Generated by Django 3.2.16 on 2023-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_testnet_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='browser',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='discord',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='facebook',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='github',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='telegram',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='wallet2_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='wallet2_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='wallet2_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='whitepaper',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='youtube',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='browser',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='discord',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='github',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet1_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet1_priv_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet1_seed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet1_session',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet2_adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet2_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet2_priv_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet2_seed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='wallet2_session',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='testnetuserinfo',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
