# Generated by Django 3.2.16 on 2023-01-19 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_testnet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnet',
            name='browser_user',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='testnet',
            name='discord_user',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='testnet',
            name='email_user',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='testnet',
            name='github_user',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='testnet',
            name='tasks_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testnet',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='testnet',
            name='testnet_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testnet_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testnet',
            name='twitter_user',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet1_adress',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet1_clue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet1_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet1_priv_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet1_seed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet1_session',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet2_adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet2_clue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet2_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet2_priv_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet2_seed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testnet',
            name='wallet2_session',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='testnet',
            name='website_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TestnetUserInfo',
        ),
    ]
