# Generated by Django 3.2.16 on 2023-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230119_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='wallet1_adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='wallet1_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='wallet1_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='wallet1_type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
