# Generated by Django 3.2.16 on 2023-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_testnet_slug_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='copied_nb',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
