# Generated by Django 3.2.16 on 2023-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_testnet_copied_nb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='testnet_name',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
