# Generated by Django 3.2.16 on 2023-01-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230122_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnet',
            name='browser_user',
        ),
    ]
