# Generated by Django 3.2.16 on 2023-01-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_testnet_browser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Blocked')], default=0),
        ),
    ]
