# Generated by Django 3.2.16 on 2023-01-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnet',
            name='status_testnet',
            field=models.IntegerField(choices=[(0, 'published'), (1, 'Archived'), (2, 'Reported')], default=0),
        ),
    ]
