# Generated by Django 3.2.16 on 2023-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_testnet_status_testnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='discord',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='status_testnet',
            field=models.IntegerField(choices=[(0, 'published'), (1, 'Deleted'), (2, 'Reported')], default=0),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='telegram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='youtube',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Blocked'), (3, 'Deleted')], default=0),
        ),
    ]
