# Generated by Django 3.2.16 on 2023-02-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230202_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='status_testnet',
            field=models.IntegerField(choices=[(0, 'published'), (2, 'Reported')], default=0),
        ),
    ]
