# Generated by Django 3.2.16 on 2023-02-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_testnet_status_testnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='category',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='network_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='slug_original',
            field=models.CharField(max_length=65),
        ),
    ]
