# Generated by Django 3.2.16 on 2023-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20230202_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='debank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Blocked')], default=0),
        ),
    ]
