# Generated by Django 3.2.16 on 2023-02-07 20:57

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20230204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='category',
            field=models.CharField(max_length=35, validators=[app.validators.starting_with_space_input]),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='description',
            field=models.TextField(db_index=True, validators=[app.validators.starting_with_space_input]),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='network_name',
            field=models.CharField(max_length=55, validators=[app.validators.starting_with_space_input]),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='network_status',
            field=models.CharField(max_length=25, validators=[app.validators.starting_with_space_input]),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='testnet_name',
            field=models.CharField(db_index=True, max_length=60, unique=True, validators=[app.validators.starting_with_space_input]),
        ),
    ]
