# Generated by Django 3.2.16 on 2023-02-07 21:05

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20230207_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='testnet_name',
            field=models.TextField(db_index=True, max_length=60, unique=True, validators=[app.validators.starting_with_space_input]),
        ),
    ]
