# Generated by Django 3.2.16 on 2023-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_testnet_testnet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='category',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='network_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='network_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='testnet',
            name='testnet_name',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
