# Generated by Django 3.2.16 on 2023-02-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20230207_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
