# Generated by Django 3.2.16 on 2023-02-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_testnet_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnet',
            name='slug_original',
            field=models.CharField(max_length=60),
        ),
    ]
